name: Starterpack - Build and upload assets and index

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v1
      with:
        name: build-${{github.sha}}
        path: build/

  upload-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build from previous step
      uses: actions/download-artifact@v1
      with:
        name: build-${{github.sha}}
    - name: Echo build files
      run: >-
        ls build-${{github.sha}}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

  upload-index:
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build index
      run: >-
        node src-index/main.js
    - name: Show index
      run: >-
        cat index.html
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
